### ISSUE TITLE
【投稿】用 Rust 从 0 到 1 实现一个最简化的 KV 存储引擎

### ISSUE THREAD

**Issue by Morgan279** [sunface/rust-weekly#8]
以实现一个最简化的 KV 存储引擎的方式学习 Rust，项目编码涉及到 Rust 中“所有权和借用”、“模式匹配”、“包和模块”、“错误处理”、“I/O操作”、“泛型和特征”，“注释和文档”等核心内容。文章链接：[https://blog.csdn.net/qq_36456827/article/details/125304612](https://blog.csdn.net/qq_36456827/article/details/125304612)，有需要的话可以提供 md 文件。

**Comment by sunface** [comment]
很棒很棒，谢谢哈～～

**Comment by Morgan279** [comment]
感谢你们收集的优质内容~ 想提一个小建议就是能不能提供一条投稿渠道和对应的审稿标准，让国内作者也有机会输出自己的内容，

**Comment by sunface** [comment]
好的，建议收到，我想想怎么搞
